-- 1. BẢNG SẢN PHẨM
-- ============================================================
create table if not exists products (
  id          bigint generated by default as identity primary key,
  name        text not null,                          -- Tên sản phẩm
  brand       text not null default 'Alokio',         -- Thương hiệu
  category    text not null default 'Loa xách tay',   -- Dòng sản phẩm
  price       numeric(12,0) not null,                 -- Giá bán (VNĐ)
  old_price   numeric(12,0),                          -- Giá gốc (null = không KM)
  description text default '',                        -- Mô tả
  specs       jsonb default '{}'::jsonb,              -- Thông số kỹ thuật {"Công suất":"800W",...}
  rating      numeric(2,1) default 5.0,               -- Điểm đánh giá 0-5
  stock       integer not null default 0,             -- Tồn kho
  featured    boolean not null default false,         -- Sản phẩm nổi bật
  created_at  timestamptz not null default now()
);

-- ============================================================
-- 2. BẢNG ẢNH SẢN PHẨM (1 sản phẩm có nhiều ảnh)
-- url: đường dẫn trong Storage bucket "media"
--      (vd: 'sản phẩm/V22 - Đen/1.png') hoặc link http đầy đủ
-- ============================================================
create table if not exists product_images (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  url        text not null,
  sort_order integer not null default 0               -- Thứ tự hiển thị (0 = ảnh đại diện)
);

create index if not exists idx_product_images_product
  on product_images(product_id);

-- ============================================================
-- 3. BẢNG VIDEO KHÁCH HÀNG (carousel trang chủ)
-- ============================================================
create table if not exists customer_videos (
  id         bigint generated by default as identity primary key,
  title      text not null default '',
  url        text not null,                           -- Đường dẫn trong bucket hoặc link http
  sort_order integer not null default 0
);

-- ============================================================
-- 4. BẢNG ĐƠN HÀNG (khách thanh toán QR trước - gửi hàng sau)
-- ============================================================
create table if not exists orders (
  id             bigint generated by default as identity primary key,
  full_name      text not null,                       -- Họ tên khách
  phone          text not null,                       -- SĐT
  email          text default '',
  address        text not null,                       -- Địa chỉ giao hàng
  total          numeric(12,0) not null,              -- Tổng tiền
  payment_method text not null default 'qr_transfer', -- Chuyển khoản QR
  -- pending_payment: chờ kiểm tra tiền | paid: đã nhận tiền
  -- shipping: đang giao | completed: hoàn thành | cancelled: hủy
  status         text not null default 'pending_payment'
                 check (status in ('pending_payment','paid','shipping','completed','cancelled')),
  note           text default '',
  created_at     timestamptz not null default now()
);

-- ============================================================
-- 5. BẢNG CHI TIẾT ĐƠN HÀNG (sản phẩm trong từng đơn)
-- ============================================================
create table if not exists order_items (
  id           bigint generated by default as identity primary key,
  order_id     bigint not null references orders(id) on delete cascade,
  product_id   bigint references products(id),
  product_name text not null,                         -- Lưu tên tại thời điểm mua
  price        numeric(12,0) not null,                -- Lưu giá tại thời điểm mua
  quantity     integer not null check (quantity > 0)
);

create index if not exists idx_order_items_order on order_items(order_id);

-- ============================================================
-- 6. BẢO MẬT (Row Level Security)
-- Khách vãng lai (anon): chỉ ĐỌC sản phẩm/ảnh/video, chỉ TẠO đơn hàng.
-- Sửa / xóa: chỉ làm được trong Dashboard (service role).
-- ============================================================
alter table products        enable row level security;
alter table product_images  enable row level security;
alter table customer_videos enable row level security;
alter table orders          enable row level security;
alter table order_items     enable row level security;

create policy "Public read products"        on products        for select using (true);
create policy "Public read product_images"  on product_images  for select using (true);
create policy "Public read customer_videos" on customer_videos for select using (true);
create policy "Public create orders"        on orders          for insert with check (true);
create policy "Public create order_items"   on order_items     for insert with check (true);

-- ============================================================
-- 7. STORAGE - bucket "media" chứa ảnh + video (công khai để web đọc)
-- Sau khi chạy SQL: vào Storage → bucket media → upload các thư mục
-- ảnh sản phẩm (giữ nguyên tên thư mục) và video.
-- ============================================================
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

create policy "Public read media"
  on storage.objects for select
  using (bucket_id = 'media');

-- ============================================================
-- 8. DỮ LIỆU MẪU - 6 SẢN PHẨM HIỆN TẠI
-- ============================================================
insert into products (id, name, brand, category, price, old_price, description, specs, rating, stock, featured) values
(1, 'Loa xách tay Alokio V22 - Đen', 'Alokio', 'Loa xách tay', 3290000, 3990000,
 'Loa xách tay karaoke Alokio V22 màu Đen sang trọng, công suất 800W với 2 bass 20 cho âm thanh mạnh mẽ, echo siêu hay. Tặng kèm combo 2 micro không dây UHF, bảo hành 12 tháng. Nhỏ gọn dễ mang theo, hát hay ở mọi nơi.',
 '{"Loại loa":"Loa xách tay karaoke","Công suất":"800W","Bass":"2 bass 20","Echo":"Echo siêu hay","Màu sắc":"Đen","Tặng kèm":"Combo 2 micro UHF","Bảo hành":"12 tháng"}',
 4.8, 15, true),
(2, 'Loa xách tay Alokio V22 - Xanh', 'Alokio', 'Loa xách tay', 3290000, 3990000,
 'Loa xách tay karaoke Alokio V22 màu Xanh trẻ trung nổi bật, công suất 800W với 2 bass 20, echo siêu hay. Tặng kèm combo 2 micro không dây UHF, bảo hành 12 tháng. Thiết kế retro tinh tế, phù hợp cả nghe nhạc lẫn hát karaoke.',
 '{"Loại loa":"Loa xách tay karaoke","Công suất":"800W","Bass":"2 bass 20","Echo":"Echo siêu hay","Màu sắc":"Xanh","Tặng kèm":"Combo 2 micro UHF","Bảo hành":"12 tháng"}',
 4.8, 12, true),
(3, 'Loa xách tay Alokio V22 - Cam', 'Alokio', 'Loa xách tay', 3290000, 3990000,
 'Loa xách tay karaoke Alokio V22 màu Cam cá tính, công suất 800W với 2 bass 20, echo siêu hay. Tặng kèm combo 2 micro không dây UHF, bảo hành 12 tháng. Gam màu ấn tượng dành cho người yêu phong cách khác biệt.',
 '{"Loại loa":"Loa xách tay karaoke","Công suất":"800W","Bass":"2 bass 20","Echo":"Echo siêu hay","Màu sắc":"Cam","Tặng kèm":"Combo 2 micro UHF","Bảo hành":"12 tháng"}',
 4.7, 8, false),
(4, 'Loa xách tay Alokio A999', 'Alokio', 'Loa xách tay', 3990000, 4590000,
 'Loa xách tay karaoke Alokio A999 công suất 900W với 2 bass 20, echo siêu hay. Tặng kèm combo 2 micro sạc UHF cao cấp, bảo hành 12 tháng. Vỏ gỗ vân sang trọng, công suất lớn nhất dòng xách tay của Alokio.',
 '{"Loại loa":"Loa xách tay karaoke","Công suất":"900W","Bass":"2 bass 20","Echo":"Echo siêu hay","Tặng kèm":"Combo 2 micro sạc UHF","Bảo hành":"12 tháng"}',
 4.9, 9, true),
(5, 'Loa xách tay Alokio A888', 'Alokio', 'Loa xách tay', 2790000, 3290000,
 'Loa xách tay karaoke Alokio A888 công suất 600W với 2 bass 20, echo siêu hay. Tặng kèm combo 2 micro không dây VHF, bảo hành 12 tháng. Thiết kế vỏ gỗ màu kem thanh lịch, mức giá dễ tiếp cận.',
 '{"Loại loa":"Loa xách tay karaoke","Công suất":"600W","Bass":"2 bass 20","Echo":"Echo siêu hay","Tặng kèm":"Combo 2 micro VHF","Bảo hành":"12 tháng"}',
 4.7, 20, true),
(6, 'Loa xách tay Alokio V20', 'Alokio', 'Loa xách tay', 1990000, 2490000,
 'Loa xách tay karaoke Alokio V20 với treble thạch anh trong trẻo, bass 20 chắc khỏe. Tặng kèm combo 2 micro không dây VHF, giao hàng miễn phí, bảo hành 12 tháng. Nhỏ gọn nhất dòng Alokio - giá mềm cho người mới bắt đầu.',
 '{"Loại loa":"Loa xách tay karaoke","Treble":"Treble thạch anh","Bass":"Bass 20","Tặng kèm":"Combo 2 micro VHF","Bảo hành":"12 tháng","Vận chuyển":"Giao hàng miễn phí"}',
 4.6, 25, false);

-- Đặt lại bộ đếm id tự tăng sau khi seed id thủ công
select setval(pg_get_serial_sequence('products', 'id'), 6, true);

-- Ảnh sản phẩm: đường dẫn trong bucket "media"
-- (upload thư mục ảnh lên Storage giữ nguyên tên là chạy)
insert into product_images (product_id, url, sort_order) values
-- V22 - Đen
(1, 'san-pham/V22---Den/1.png', 0),(1, 'san-pham/V22---Den/2.png', 1),
(1, 'san-pham/V22---Den/3.png', 2),(1, 'san-pham/V22---Den/4.png', 3),
(1, 'san-pham/V22---Den/5.png', 4),(1, 'san-pham/V22---Den/6.png', 5),
(1, 'san-pham/V22---Den/7.png', 6),
-- V22 - Xanh
(2, 'san-pham/V22---Xanh/1.png', 0),(2, 'san-pham/V22---Xanh/2.png', 1),
(2, 'san-pham/V22---Xanh/3.png', 2),(2, 'san-pham/V22---Xanh/4.png', 3),
(2, 'san-pham/V22---Xanh/5.png', 4),(2, 'san-pham/V22---Xanh/6.png', 5),
(2, 'san-pham/V22---Xanh/7.png', 6),
-- V22 - Cam
(3, 'san-pham/V22---CAm/1.png', 0),(3, 'san-pham/V22---CAm/12.png', 1),
(3, 'san-pham/V22---CAm/13.png', 2),(3, 'san-pham/V22---CAm/14.png', 3),
(3, 'san-pham/V22---CAm/16.png', 4),(3, 'san-pham/V22---CAm/17.png', 5),
(3, 'san-pham/V22---CAm/22.png', 6),
-- A999
(4, 'san-pham/A999/1.png', 0),(4, 'san-pham/A999/2.png', 1),
(4, 'san-pham/A999/3.png', 2),(4, 'san-pham/A999/4.png', 3),
(4, 'san-pham/A999/5.png', 4),(4, 'san-pham/A999/6.png', 5),
(4, 'san-pham/A999/7.png', 6),(4, 'san-pham/A999/8.png', 7),
-- A888
(5, 'san-pham/A888/1.png', 0),(5, 'san-pham/A888/2.png', 1),
(5, 'san-pham/A888/3.png', 2),(5, 'san-pham/A888/4.png', 3),
(5, 'san-pham/A888/5.png', 4),(5, 'san-pham/A888/6.png', 5),
(5, 'san-pham/A888/7.png', 6),(5, 'san-pham/A888/8.png', 7),
(5, 'san-pham/A888/9.png', 8),(5, 'san-pham/A888/10.png', 9),
(5, 'san-pham/A888/11.png', 10),
-- V20
(6, 'san-pham/V20/23.png', 0),(6, 'san-pham/V20/25.png', 1),
(6, 'san-pham/V20/27.png', 2),(6, 'san-pham/V20/28.png', 3),
(6, 'san-pham/V20/29.png', 4),(6, 'san-pham/V20/30.png', 5),
(6, 'san-pham/V20/31.png', 6),(6, 'san-pham/V20/32.png', 7),
(6, 'san-pham/V20/33.png', 8),(6, 'san-pham/V20/34.png', 9),
(6, 'san-pham/V20/35.png', 10);

-- Video khách hát
insert into customer_videos (title, url, sort_order) values
('Khách hát thử cùng loa Alokio',           'san-pham/7903426131505.mp4', 0),
('Trải nghiệm karaoke tại cửa hàng',         'san-pham/7903425700253.mp4', 1),
('Giọng hát khách hàng cùng micro Alokio',   'san-pham/7903425011264.mp4', 2),
('Khách trải nghiệm loa Alokio tại cửa hàng','san-pham/7903765725081.mp4', 3);

-- ============================================================
-- 9. BẢNG BÀI VIẾT / TIN TỨC (ARTICLES)
-- ============================================================
create table if not exists articles (
  id          bigint generated by default as identity primary key,
  title       text not null,
  summary     text not null,
  content     text not null,
  image_url   text default '',
  created_at  timestamptz not null default now()
);

alter table articles enable row level security;
create policy "Public read articles" on articles for select using (true);

insert into articles (title, summary, content, image_url) values
('Loa Alokio V22 – Loa Kéo Karaoke Bluetooth 800W Đáng Mua Nhất Hiện Nay',
 'Loa Alokio V22 đang là một trong những sản phẩm được nhiều khách hàng lựa chọn nhờ thiết kế đẹp mắt, âm thanh mạnh mẽ và khả năng kết nối linh hoạt.',
 'Trong phân khúc loa kéo karaoke tầm trung, loa Alokio V22 đang là một trong những sản phẩm được nhiều khách hàng lựa chọn nhờ thiết kế đẹp mắt, âm thanh mạnh mẽ và khả năng kết nối linh hoạt. Sở hữu công suất lên đến 800W cùng hệ thống 2 bass 20cm, Alokio V22 mang đến trải nghiệm nghe nhạc và hát karaoke sống động, đáp ứng tốt nhu cầu giải trí gia đình cũng như các hoạt động ngoài trời.

Thiết Kế Sang Trọng, Chắc Chắn
Loa kéo Alokio V22 được thiết kế với thùng gỗ bọc da cao cấp, tạo cảm giác sang trọng và bền bỉ trong quá trình sử dụng. Các góc loa được gia cố chắc chắn giúp hạn chế va đập khi di chuyển. Hệ thống bánh xe và tay kéo tiện lợi giúp người dùng dễ dàng mang theo trong các chuyến dã ngoại, tiệc tùng hoặc sự kiện ngoài trời.

Âm Thanh Mạnh Mẽ Với Công Suất 800W
Điểm nổi bật của loa karaoke Alokio V22 chính là công suất lớn lên đến 800W. Hệ thống 2 loa bass 20cm kết hợp cùng treble chất lượng cao cho âm thanh cân bằng, bass mạnh, trung âm rõ ràng và treble trong trẻo.

Tặng Kèm 2 Micro UHF Cao Cấp
Sản phẩm được trang bị 2 micro không dây UHF giúp bắt sóng xa, chống hú hiệu quả và cho chất lượng giọng hát rõ ràng. Đây là ưu điểm giúp loa Alokio V22 trở thành lựa chọn lý tưởng cho những người yêu thích karaoke.

Có Nên Mua Loa Alokio V22 Không?
Nếu bạn đang tìm kiếm một chiếc loa kéo karaoke Bluetooth có âm thanh mạnh mẽ, thiết kế đẹp và mức giá hợp lý thì loa Alokio V22 là lựa chọn rất đáng cân nhắc.',
 'san-pham/V22---Den/1.png'),

('Loa Kéo Karaoke Alokio A999 Chính Hãng – 2 Bass 20, Công Suất 900W, Micro Sạc UHF',
 'Alokio A999 là một trong những sản phẩm nổi bật nhờ thiết kế sang trọng, chất âm mạnh mẽ và khả năng kết nối đa dạng.',
 'Trong phân khúc loa kéo karaoke gia đình và kinh doanh hiện nay, Alokio A999 là một trong những sản phẩm nổi bật nhờ thiết kế sang trọng, chất âm mạnh mẽ và khả năng kết nối đa dạng. Được trang bị hệ thống 2 bass 20cm, công suất lên đến 900W cùng 2 micro sạc UHF cao cấp, Alokio A999 mang đến trải nghiệm giải trí sống động cho mọi không gian sử dụng.

Thiết Kế Thùng Vân Gỗ Cao Cấp, Sang Trọng
Loa Alokio A999 sở hữu thiết kế thùng gỗ vân cao cấp với gam màu nâu sang trọng, mang lại cảm giác chắc chắn và đẳng cấp ngay từ cái nhìn đầu tiên.

Âm Thanh Uy Lực Với Hệ Thống 2 Bass 20 Và Công Suất 900W
Điểm mạnh nổi bật của loa kéo Alokio A999 chính là khả năng tái tạo âm thanh mạnh mẽ nhờ hệ thống 2 bass 20cm kết hợp cùng 2 treble thạch anh cao cấp.

Micro Sạc UHF Cao Cấp – Hát Nhẹ, Hạn Chế Hú Rít
Sản phẩm được trang bị sẵn 2 micro sạc UHF không dây cao cấp với khả năng bắt sóng ổn định, hút âm tốt và hạn chế hú rít hiệu quả.

Vì Sao Nên Chọn Loa Kéo Alokio A999?
Thiết kế thùng vân gỗ sang trọng, công suất lớn 900W mạnh mẽ, hệ thống 2 bass 20 cho âm thanh uy lực, 2 micro sạc UHF cao cấp đi kèm.',
 'san-pham/A999/1.png'),

('Loa Kéo Karaoke Alokio V20 Chính Hãng – Bass 20, 2 Micro VHF, Thùng Gỗ Bọc Da Sang Trọng',
 'Nếu bạn đang tìm kiếm một chiếc loa karaoke di động nhỏ gọn, dễ sử dụng nhưng vẫn đáp ứng tốt nhu cầu nghe nhạc và hát karaoke thì Alokio V20 là lựa chọn đáng cân nhắc.',
 'Nếu bạn đang tìm kiếm một chiếc loa karaoke di động nhỏ gọn, dễ sử dụng nhưng vẫn đáp ứng tốt nhu cầu nghe nhạc và hát karaoke thì Alokio V20 là lựa chọn đáng cân nhắc. Với thiết kế thùng gỗ bọc da cao cấp, hệ thống Bass 20cm cùng 2 micro không dây VHF đi kèm, Alokio V20 mang đến trải nghiệm giải trí tiện lợi cho gia đình, quán cà phê, bán hàng hoặc các buổi dã ngoại ngoài trời.

Thiết Kế Thùng Gỗ Bọc Da Sang Trọng
Loa Alokio V20 được thiết kế theo phong cách cổ điển với lớp bọc da cao cấp kết hợp thùng gỗ chắc chắn.

Âm Thanh Rõ Ràng Với Bass 20 Và Treble Thạch Anh
Hệ thống loa cho âm bass trầm chắc, tiếng hát rõ ràng và treble sáng trong. Dù sử dụng để nghe nhạc hay hát karaoke, Alokio V20 vẫn mang lại trải nghiệm âm thanh dễ chịu và ổn định.

Trang Bị 2 Micro Không Dây VHF
Loa đi kèm 2 micro không dây VHF giúp người dùng có thể hát song ca cùng bạn bè và người thân.

Pin Sạc Tiện Lợi, Hỗ Trợ Dùng Điện Trực Tiếp
Loa được trang bị pin 15V – 3Ah cho thời gian sử dụng linh hoạt: Karaoke liên tục từ 2 – 4 giờ, nghe nhạc từ 4 – 6 giờ.',
 'san-pham/V20/23.png'),

('Loa Kéo Karaoke Alokio A888 Chính Hãng – 2 Bass 20, Công Suất 600W, Thiết Kế Sang Trọng',
 'Alokio A888 là mẫu loa kéo karaoke Bluetooth nổi bật với thiết kế hiện đại, màu sắc sang trọng cùng chất lượng âm thanh mạnh mẽ.',
 'Alokio A888 là mẫu loa kéo karaoke Bluetooth nổi bật với thiết kế hiện đại, màu sắc sang trọng cùng chất lượng âm thanh mạnh mẽ. Sản phẩm được nhiều gia đình lựa chọn nhờ khả năng hát karaoke ổn định, dễ sử dụng và mức giá hợp lý. Với hệ thống 2 bass 20cm, công suất 600W cùng 2 micro không dây VHF đi kèm, Alokio A888 đáp ứng tốt nhu cầu nghe nhạc, hát karaoke.

Thiết Kế Bọc Da Cao Cấp, Màu Vàng Be Sang Trọng
Loa Alokio A888 sở hữu thiết kế thùng gỗ bọc da cao cấp với tông màu vàng be hiện đại, tạo điểm nhấn nổi bật trong mọi không gian sử dụng.

Âm Thanh Mạnh Mẽ Với 2 Bass 20 Và Công Suất 600W
Điểm nổi bật của loa kéo Alokio A888 là hệ thống âm thanh gồm 2 Bass 20cm và 1 Treble Thạch Anh. Công suất 600W cho khả năng phủ âm tốt trong không gian phòng khách, sân vườn, quán cà phê.

Trang Bị 2 Micro Không Dây VHF
Alokio A888 được tặng kèm 2 micro không dây VHF chất lượng cao. Micro có độ nhạy tốt, khả năng bắt tiếng ổn định, hỗ trợ hát karaoke nhẹ giọng và hạn chế hú rít trong quá trình sử dụng.',
 'san-pham/A888/1.png');
